MED-102 Implement Booking 1 UI
ZenBit-Tech/MedOn_fe pull request #34
Opened 2023-05-08 12:13 UTC by SoulOfDarknes

1. Add IU 1 step Booking [Appointments]
2. Add patient info
**PR checklist:**

**1.1 Common**
- [x] 1.1.2 no any, should be also added to eslint rules
- [x] 1.1.1 types for input and output params
- [x] 1.1.3 try/catch for any async function
- [x] 1.1.4 no magic numbers
- [x] 1.1.5 compare only with constants not with strings (instead of user === ‘admin’, better user === roles.admin)
- [x] 1.1.6 no ternary operator inside ternary operator (bad example: question ? first: second ? third: fourth)
- [x] 1.1.7 avoid similar types with duplicating by generics
- [x] 1.1.8 no console.log in pr
- [x] 1.1.9 .env file should be in .gitignore
- [x] 1.1.10 delete commented code if it's not part of documentation
- [x] 1.1.11 no links in the code, env links should be in env file (for example: server url),
- [x] constant links (for example default avatar URL) should be in constant file
- [x] 1.1.12 constants and function names should be lowercase.
- [x] 1.1.13 no dates format in the code (like "dd/MM/yyyy”), move it in global constant variable
- [x] 1.1.14 import rules. imports should come in a specific order: node modules, absolute path, relative path
- [x] 1.1.15 strings should be in the constant variable. Example: instead of ‘15 3 * * *’, const EACH_DAY_15h_15min = ‘15 3 * * *’

 **1.3 Frontend|Mobile**
- [x] 1.3.1 split component and logic (move logic to custom hook file)
- [x] 1.3.2 colors, font size, and font name should be in the theme or in the constants
- [x] 1.3.3 no text in the components, use i18n approach, even if you have only one language for now
- [x] 1.3.4 inline styles prohibited
- [x] 1.3.5 import should be absolute. instead of ../../../components/myComponent should be components/myComponent

![image](https://user-images.githubusercontent.com/89462761/236820422-256bb88d-4411-4638-8a1b-5d3e5ef7ff33.png)

![image](https://user-images.githubusercontent.com/89462761/236820868-dd5a51dc-ff69-440b-a246-a1ca70f15845.png)

2023-05-08 13:44 UTC, skazzp requested changes

2023-05-08 13:44 UTC, skazzp commented on apps/medon-fe/src/components/Steps/styles.tsx
> +  background-image: url(/assets/svgs/cross.svg);
path to const

2023-05-08 13:44 UTC, skazzp commented on apps/medon-fe/src/components/Steps/styles.tsx
> +    background-image: url(/assets/svgs/appointments/arrowRight.svg);
same

2023-05-10 19:39 UTC, SoulOfDarknes commented on apps/medon-fe/src/components/Steps/styles.tsx
> +  background-image: url(/assets/svgs/cross.svg);
done

2023-05-10 19:39 UTC, SoulOfDarknes commented on apps/medon-fe/src/components/Steps/styles.tsx
> +    background-image: url(/assets/svgs/appointments/arrowRight.svg);
done

2023-05-10 20:19 UTC, skazzp requested changes

2023-05-10 20:19 UTC, skazzp commented on apps/medon-fe/src/components/BookAppointmentCalendar/index.tsx
> +            return localizer.format(date, 'dddd', culture);
date format to const

2023-05-11 09:55 UTC, SoulOfDarknes commented on apps/medon-fe/src/components/BookAppointmentCalendar/index.tsx
> +            return localizer.format(date, 'dddd', culture);
done

2023-05-11 12:01 UTC, skazzp approved these changes

2023-05-15 16:33 UTC, lyudad commented on apps/medon-fe/src/components/Steps/index.tsx
> +  const getDoctorFullName = (doctorId: number) => {
it will be called with each rerender, does it ok?

2023-05-15 16:33 UTC, lyudad commented on apps/medon-fe/src/components/Steps/index.tsx
> +  const getDoctorFullName = (doctorId: number) => {
whare is output types?

2023-05-15 16:33 UTC, lyudad commented on apps/medon-fe/src/components/Steps/styles.tsx
> +      buttonType === 'next'
we are con compare with text

2023-05-18 17:12 UTC, SoulOfDarknes commented on apps/medon-fe/src/components/Steps/index.tsx
> +  const getDoctorFullName = (doctorId: number) => {
fixed rewrites and put it to different file

2023-05-18 17:37 UTC, SoulOfDarknes commented on apps/medon-fe/src/components/Steps/styles.tsx
> +      buttonType === 'next'
fixed

2023-05-18 19:09 UTC, lyudad commented on apps/medon-fe/src/components/BookAppointmentCalendar/index.tsx
> +          culture: string | undefined,
culture?: string should work

2023-05-18 19:19 UTC, SoulOfDarknes commented on apps/medon-fe/src/components/BookAppointmentCalendar/index.tsx
> +          culture: string | undefined,
fixed

2023-05-22 19:11 UTC, merged